---
# Per environment values which override defaults in srrc-capture-finger-prints/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: srrc-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: srrc-preprod-cert
  env:
    INGRESS_URL: "https://srrc-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://srrc-api-preprod.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
